// port-lint: source src/default_types.rs
package io.github.kotlinmania.ignore

/** This list represents the default file types that ripgrep ships with. In
 * general, any file format is fair game, although it should generally be
 * limited to reasonably popular open formats. For other cases, you can add
 * types to each invocation of ripgrep with the `--type-add` flag.
 *
 * If you would like to add or improve this list, please file a PR:
 * https://github.com/BurntSushi/ripgrep.
 *
 * Please try to keep this list sorted lexicographically. */
internal val DEFAULT_TYPES: Array<Pair<Array<String>, Array<String>>> = arrayOf(
    Pair(arrayOf("ada"), arrayOf("*.adb", "*.ads")),
    Pair(arrayOf("agda"), arrayOf("*.agda", "*.lagda")),
    Pair(arrayOf("aidl"), arrayOf("*.aidl")),
    Pair(arrayOf("alire"), arrayOf("alire.toml")),
    Pair(arrayOf("amake"), arrayOf("*.mk", "*.bp")),
    Pair(arrayOf("asciidoc"), arrayOf("*.adoc", "*.asc", "*.asciidoc")),
    Pair(arrayOf("asm"), arrayOf("*.asm", "*.s", "*.S")),
    Pair(arrayOf("asp"), arrayOf(
        "*.aspx", "*.aspx.cs", "*.aspx.vb", "*.ascx", "*.ascx.cs",
        "*.ascx.vb", "*.asp",
    )),
    Pair(arrayOf("ats"), arrayOf("*.ats", "*.dats", "*.sats", "*.hats")),
    Pair(arrayOf("avro"), arrayOf("*.avdl", "*.avpr", "*.avsc")),
    Pair(arrayOf("awk"), arrayOf("*.awk")),
    Pair(arrayOf("bat", "batch"), arrayOf("*.bat")),
    Pair(arrayOf("bazel"), arrayOf(
        "*.bazel", "*.bzl", "*.BUILD", "*.bazelrc", "BUILD", "MODULE.bazel",
        "WORKSPACE", "WORKSPACE.bazel", "WORKSPACE.bzlmod",
    )),
    Pair(arrayOf("bitbake"), arrayOf("*.bb", "*.bbappend", "*.bbclass", "*.conf", "*.inc")),
    Pair(arrayOf("boxlang"), arrayOf("*.bx", "*.bxm", "*.bxs")),
    Pair(arrayOf("brotli"), arrayOf("*.br")),
    Pair(arrayOf("buildstream"), arrayOf("*.bst")),
    Pair(arrayOf("bzip2"), arrayOf("*.bz2", "*.tbz2")),
    Pair(arrayOf("c"), arrayOf("*.[chH]", "*.[chH].in", "*.cats")),
    Pair(arrayOf("cabal"), arrayOf("*.cabal")),
    Pair(arrayOf("candid"), arrayOf("*.did")),
    Pair(arrayOf("carp"), arrayOf("*.carp")),
    Pair(arrayOf("cbor"), arrayOf("*.cbor")),
    Pair(arrayOf("ceylon"), arrayOf("*.ceylon")),
    Pair(arrayOf("cfml"), arrayOf("*.cfc", "*.cfm")),
    Pair(arrayOf("clojure"), arrayOf("*.clj", "*.cljc", "*.cljs", "*.cljx")),
    Pair(arrayOf("cmake"), arrayOf("*.cmake", "CMakeLists.txt")),
    Pair(arrayOf("cmd"), arrayOf("*.bat", "*.cmd")),
    Pair(arrayOf("cml"), arrayOf("*.cml")),
    Pair(arrayOf("coffeescript"), arrayOf("*.coffee")),
    Pair(arrayOf("config"), arrayOf("*.cfg", "*.conf", "*.config", "*.ini")),
    Pair(arrayOf("container"), arrayOf("*Containerfile*", "*Dockerfile*")),
    Pair(arrayOf("coq"), arrayOf("*.v")),
    Pair(arrayOf("cpp"), arrayOf(
        "*.[ChH]", "*.cc", "*.[ch]pp", "*.[ch]xx", "*.hh", "*.inl",
        "*.[ChH].in", "*.cc.in", "*.[ch]pp.in", "*.[ch]xx.in", "*.hh.in",
    )),
    Pair(arrayOf("creole"), arrayOf("*.creole")),
    Pair(arrayOf("crystal"), arrayOf("Projectfile", "*.cr", "*.ecr", "shard.yml")),
    Pair(arrayOf("cs"), arrayOf("*.cs")),
    Pair(arrayOf("csharp"), arrayOf("*.cs")),
    Pair(arrayOf("cshtml"), arrayOf("*.cshtml")),
    Pair(arrayOf("csproj"), arrayOf("*.csproj")),
    Pair(arrayOf("css"), arrayOf("*.css", "*.scss")),
    Pair(arrayOf("csv"), arrayOf("*.csv")),
    Pair(arrayOf("cuda"), arrayOf("*.cu", "*.cuh")),
    Pair(arrayOf("cython"), arrayOf("*.pyx", "*.pxi", "*.pxd")),
    Pair(arrayOf("d"), arrayOf("*.d")),
    Pair(arrayOf("dart"), arrayOf("*.dart")),
    Pair(arrayOf("devicetree"), arrayOf("*.dts", "*.dtsi", "*.dtso")),
    Pair(arrayOf("dhall"), arrayOf("*.dhall")),
    Pair(arrayOf("diff"), arrayOf("*.patch", "*.diff")),
    Pair(arrayOf("dita"), arrayOf("*.dita", "*.ditamap", "*.ditaval")),
    Pair(arrayOf("docker"), arrayOf("*Dockerfile*")),
    Pair(arrayOf("dockercompose"), arrayOf("docker-compose.yml", "docker-compose.*.yml")),
    Pair(arrayOf("dts"), arrayOf("*.dts", "*.dtsi")),
    Pair(arrayOf("dvc"), arrayOf("Dvcfile", "*.dvc")),
    Pair(arrayOf("ebuild"), arrayOf("*.ebuild", "*.eclass")),
    Pair(arrayOf("edn"), arrayOf("*.edn")),
    Pair(arrayOf("elisp"), arrayOf("*.el")),
    Pair(arrayOf("elixir"), arrayOf("*.ex", "*.eex", "*.exs", "*.heex", "*.leex", "*.livemd")),
    Pair(arrayOf("elm"), arrayOf("*.elm")),
    Pair(arrayOf("erb"), arrayOf("*.erb")),
    Pair(arrayOf("erlang"), arrayOf("*.erl", "*.hrl")),
    Pair(arrayOf("fennel"), arrayOf("*.fnl")),
    Pair(arrayOf("fidl"), arrayOf("*.fidl")),
    Pair(arrayOf("fish"), arrayOf("*.fish")),
    Pair(arrayOf("flatbuffers"), arrayOf("*.fbs")),
    Pair(arrayOf("fortran"), arrayOf(
        "*.f", "*.F", "*.f77", "*.F77", "*.pfo",
        "*.f90", "*.F90", "*.f95", "*.F95",
    )),
    Pair(arrayOf("fsharp"), arrayOf("*.fs", "*.fsx", "*.fsi")),
    Pair(arrayOf("fut"), arrayOf("*.fut")),
    Pair(arrayOf("gap"), arrayOf("*.g", "*.gap", "*.gi", "*.gd", "*.tst")),
    Pair(arrayOf("gdscript"), arrayOf("*.gd")),
    Pair(arrayOf("gleam"), arrayOf("*.gleam")),
    Pair(arrayOf("gn"), arrayOf("*.gn", "*.gni")),
    Pair(arrayOf("go"), arrayOf("*.go")),
    Pair(arrayOf("gprbuild"), arrayOf("*.gpr")),
    Pair(arrayOf("gradle"), arrayOf(
        "*.gradle", "*.gradle.kts", "gradle.properties", "gradle-wrapper.*",
        "gradlew", "gradlew.bat",
    )),
    Pair(arrayOf("graphql"), arrayOf("*.graphql", "*.graphqls")),
    Pair(arrayOf("groovy"), arrayOf("*.groovy", "*.gradle")),
    Pair(arrayOf("gzip"), arrayOf("*.gz", "*.tgz")),
    Pair(arrayOf("h"), arrayOf("*.h", "*.hh", "*.hpp")),
    Pair(arrayOf("haml"), arrayOf("*.haml")),
    Pair(arrayOf("hare"), arrayOf("*.ha")),
    Pair(arrayOf("haskell"), arrayOf("*.hs", "*.lhs", "*.cpphs", "*.c2hs", "*.hsc")),
    Pair(arrayOf("hbs"), arrayOf("*.hbs")),
    Pair(arrayOf("hs"), arrayOf("*.hs", "*.lhs")),
    Pair(arrayOf("html"), arrayOf("*.htm", "*.html", "*.ejs")),
    Pair(arrayOf("hy"), arrayOf("*.hy")),
    Pair(arrayOf("idris"), arrayOf("*.idr", "*.lidr")),
    Pair(arrayOf("janet"), arrayOf("*.janet")),
    Pair(arrayOf("java"), arrayOf("*.java", "*.jsp", "*.jspx", "*.properties")),
    Pair(arrayOf("jinja"), arrayOf("*.j2", "*.jinja", "*.jinja2")),
    Pair(arrayOf("jl"), arrayOf("*.jl")),
    Pair(arrayOf("js"), arrayOf("*.js", "*.jsx", "*.vue", "*.cjs", "*.mjs")),
    Pair(arrayOf("json"), arrayOf("*.json", "composer.lock", "*.sarif")),
    Pair(arrayOf("jsonl"), arrayOf("*.jsonl")),
    Pair(arrayOf("julia"), arrayOf("*.jl")),
    Pair(arrayOf("jupyter"), arrayOf("*.ipynb", "*.jpynb")),
    Pair(arrayOf("k"), arrayOf("*.k")),
    Pair(arrayOf("kconfig"), arrayOf("Kconfig", "Kconfig.*")),
    Pair(arrayOf("kotlin"), arrayOf("*.kt", "*.kts")),
    Pair(arrayOf("lean"), arrayOf("*.lean")),
    Pair(arrayOf("less"), arrayOf("*.less")),
    Pair(arrayOf("license"), arrayOf(
        // General
        "COPYING", "COPYING[.-]*",
        "COPYRIGHT", "COPYRIGHT[.-]*",
        "EULA", "EULA[.-]*",
        "licen[cs]e", "licen[cs]e.*",
        "LICEN[CS]E", "LICEN[CS]E[.-]*", "*[.-]LICEN[CS]E*",
        "NOTICE", "NOTICE[.-]*",
        "PATENTS", "PATENTS[.-]*",
        "UNLICEN[CS]E", "UNLICEN[CS]E[.-]*",
        // GPL (gpl.txt, etc.)
        "agpl[.-]*",
        "gpl[.-]*",
        "lgpl[.-]*",
        // Other license-specific (APACHE-2.0.txt, etc.)
        "AGPL-*[0-9]*",
        "APACHE-*[0-9]*",
        "BSD-*[0-9]*",
        "CC-BY-*",
        "GFDL-*[0-9]*",
        "GNU-*[0-9]*",
        "GPL-*[0-9]*",
        "LGPL-*[0-9]*",
        "MIT-*[0-9]*",
        "MPL-*[0-9]*",
        "OFL-*[0-9]*",
    )),
    Pair(arrayOf("lilypond"), arrayOf("*.ly", "*.ily")),
    Pair(arrayOf("lisp"), arrayOf("*.el", "*.jl", "*.lisp", "*.lsp", "*.sc", "*.scm")),
    Pair(arrayOf("llvm"), arrayOf("*.ll")),
    Pair(arrayOf("lock"), arrayOf("*.lock", "package-lock.json")),
    Pair(arrayOf("log"), arrayOf("*.log")),
    Pair(arrayOf("lua"), arrayOf("*.lua")),
    Pair(arrayOf("lz4"), arrayOf("*.lz4")),
    Pair(arrayOf("lzma"), arrayOf("*.lzma")),
    Pair(arrayOf("m4"), arrayOf("*.ac", "*.m4")),
    Pair(arrayOf("make"), arrayOf(
        "[Gg][Nn][Uu]makefile", "[Mm]akefile",
        "[Gg][Nn][Uu]makefile.am", "[Mm]akefile.am",
        "[Gg][Nn][Uu]makefile.in", "[Mm]akefile.in",
        "Makefile.*",
        "*.mk", "*.mak",
    )),
    Pair(arrayOf("mako"), arrayOf("*.mako", "*.mao")),
    Pair(arrayOf("man"), arrayOf("*.[0-9lnpx]", "*.[0-9][cEFMmpSx]")),
    Pair(arrayOf("markdown", "md"), arrayOf(
        "*.markdown",
        "*.md",
        "*.mdown",
        "*.mdwn",
        "*.mkd",
        "*.mkdn",
        "*.mdx",
    )),
    Pair(arrayOf("matlab"), arrayOf("*.m")),
    Pair(arrayOf("meson"), arrayOf("meson.build", "meson_options.txt", "meson.options")),
    Pair(arrayOf("minified"), arrayOf("*.min.html", "*.min.css", "*.min.js")),
    Pair(arrayOf("mint"), arrayOf("*.mint")),
    Pair(arrayOf("mk"), arrayOf("mkfile")),
    Pair(arrayOf("ml"), arrayOf("*.ml")),
    Pair(arrayOf("motoko"), arrayOf("*.mo")),
    Pair(arrayOf("msbuild"), arrayOf(
        "*.csproj", "*.fsproj", "*.vcxproj", "*.proj", "*.props", "*.targets",
        "*.sln", "*.slnf",
    )),
    Pair(arrayOf("nim"), arrayOf("*.nim", "*.nimf", "*.nimble", "*.nims")),
    Pair(arrayOf("nix"), arrayOf("*.nix")),
    Pair(arrayOf("objc"), arrayOf("*.h", "*.m")),
    Pair(arrayOf("objcpp"), arrayOf("*.h", "*.mm")),
    Pair(arrayOf("ocaml"), arrayOf("*.ml", "*.mli", "*.mll", "*.mly")),
    Pair(arrayOf("org"), arrayOf("*.org", "*.org_archive")),
    Pair(arrayOf("pants"), arrayOf("BUILD")),
    Pair(arrayOf("pascal"), arrayOf("*.pas", "*.dpr", "*.lpr", "*.pp", "*.inc")),
    Pair(arrayOf("pdf"), arrayOf("*.pdf")),
    Pair(arrayOf("perl"), arrayOf("*.perl", "*.pl", "*.PL", "*.plh", "*.plx", "*.pm", "*.t")),
    Pair(arrayOf("php"), arrayOf(
        // note that PHP 6 doesn't exist
        // See: https://wiki.php.net/rfc/php6
        "*.php", "*.php3", "*.php4", "*.php5", "*.php7", "*.php8",
        "*.pht", "*.phtml",
    )),
    Pair(arrayOf("po"), arrayOf("*.po")),
    Pair(arrayOf("pod"), arrayOf("*.pod")),
    Pair(arrayOf("postscript"), arrayOf("*.eps", "*.ps")),
    Pair(arrayOf("prolog"), arrayOf("*.pl", "*.pro", "*.prolog", "*.P")),
    Pair(arrayOf("protobuf"), arrayOf("*.proto")),
    Pair(arrayOf("ps"), arrayOf("*.cdxml", "*.ps1", "*.ps1xml", "*.psd1", "*.psm1")),
    Pair(arrayOf("puppet"), arrayOf("*.epp", "*.erb", "*.pp", "*.rb")),
    Pair(arrayOf("purs"), arrayOf("*.purs")),
    Pair(arrayOf("py", "python"), arrayOf("*.py", "*.pyi")),
    Pair(arrayOf("qmake"), arrayOf("*.pro", "*.pri", "*.prf")),
    Pair(arrayOf("qml"), arrayOf("*.qml")),
    Pair(arrayOf("qrc"), arrayOf("*.qrc")),
    Pair(arrayOf("qui"), arrayOf("*.ui")),
    Pair(arrayOf("r"), arrayOf("*.R", "*.r", "*.Rmd", "*.rmd", "*.Rnw", "*.rnw")),
    Pair(arrayOf("racket"), arrayOf("*.rkt")),
    Pair(arrayOf("raku"), arrayOf(
        "*.raku", "*.rakumod", "*.rakudoc", "*.rakutest",
        "*.p6", "*.pl6", "*.pm6",
    )),
    Pair(arrayOf("rdoc"), arrayOf("*.rdoc")),
    Pair(arrayOf("readme"), arrayOf("README*", "*README")),
    Pair(arrayOf("reasonml"), arrayOf("*.re", "*.rei")),
    Pair(arrayOf("red"), arrayOf("*.r", "*.red", "*.reds")),
    Pair(arrayOf("rescript"), arrayOf("*.res", "*.resi")),
    Pair(arrayOf("robot"), arrayOf("*.robot")),
    Pair(arrayOf("rst"), arrayOf("*.rst")),
    Pair(arrayOf("ruby"), arrayOf(
        // Idiomatic files
        "config.ru", "Gemfile", ".irbrc", "Rakefile",
        // Extensions
        "*.gemspec", "*.rb", "*.rbw", "*.rake",
    )),
    Pair(arrayOf("rust"), arrayOf("*.rs")),
    Pair(arrayOf("sass"), arrayOf("*.sass", "*.scss")),
    Pair(arrayOf("scala"), arrayOf("*.scala", "*.sbt")),
    Pair(arrayOf("scdoc"), arrayOf("*.scd", "*.scdoc")),
    Pair(arrayOf("seed7"), arrayOf("*.sd7", "*.s7i")),
    Pair(arrayOf("sh"), arrayOf(
        // Portable/misc. init files
        ".env", ".login", ".logout", ".profile", "profile",
        // bash-specific init files
        ".bash_login", "bash_login",
        ".bash_logout", "bash_logout",
        ".bash_profile", "bash_profile",
        ".bashrc", "bashrc", "*.bashrc",
        // csh-specific init files
        ".cshrc", "*.cshrc",
        // ksh-specific init files
        ".kshrc", "*.kshrc",
        // tcsh-specific init files
        ".tcshrc",
        // zsh-specific init files
        ".zshenv", "zshenv",
        ".zlogin", "zlogin",
        ".zlogout", "zlogout",
        ".zprofile", "zprofile",
        ".zshrc", "zshrc",
        // Extensions
        "*.bash", "*.csh", "*.env", "*.ksh", "*.sh", "*.tcsh", "*.zsh",
    )),
    Pair(arrayOf("slim"), arrayOf("*.skim", "*.slim", "*.slime")),
    Pair(arrayOf("smarty"), arrayOf("*.tpl")),
    Pair(arrayOf("sml"), arrayOf("*.sml", "*.sig")),
    Pair(arrayOf("solidity"), arrayOf("*.sol")),
    Pair(arrayOf("soy"), arrayOf("*.soy")),
    Pair(arrayOf("spark"), arrayOf("*.spark")),
    Pair(arrayOf("spec"), arrayOf("*.spec")),
    Pair(arrayOf("sql"), arrayOf("*.sql", "*.psql")),
    Pair(arrayOf("ssa"), arrayOf("*.ssa")),
    Pair(arrayOf("stylus"), arrayOf("*.styl")),
    Pair(arrayOf("sv"), arrayOf("*.v", "*.vg", "*.sv", "*.svh", "*.h")),
    Pair(arrayOf("svelte"), arrayOf("*.svelte", "*.svelte.ts")),
    Pair(arrayOf("svg"), arrayOf("*.svg")),
    Pair(arrayOf("swift"), arrayOf("*.swift")),
    Pair(arrayOf("swig"), arrayOf("*.def", "*.i")),
    Pair(arrayOf("systemd"), arrayOf(
        "*.automount", "*.conf", "*.device", "*.link", "*.mount", "*.path",
        "*.scope", "*.service", "*.slice", "*.socket", "*.swap", "*.target",
        "*.timer",
    )),
    Pair(arrayOf("taskpaper"), arrayOf("*.taskpaper")),
    Pair(arrayOf("tcl"), arrayOf("*.tcl")),
    Pair(arrayOf("tex"), arrayOf("*.tex", "*.ltx", "*.cls", "*.sty", "*.bib", "*.dtx", "*.ins")),
    Pair(arrayOf("texinfo"), arrayOf("*.texi")),
    Pair(arrayOf("textile"), arrayOf("*.textile")),
    Pair(arrayOf("tf"), arrayOf(
        "*.tf", "*.tf.json", "*.tfvars", "*.tfvars.json",
        "*.terraformrc", "terraform.rc", "*.tfrc", "*.terraform.lock.hcl",
    )),
    Pair(arrayOf("thrift"), arrayOf("*.thrift")),
    Pair(arrayOf("toml"), arrayOf("*.toml", "Cargo.lock")),
    Pair(arrayOf("ts", "typescript"), arrayOf("*.ts", "*.tsx", "*.cts", "*.mts")),
    Pair(arrayOf("twig"), arrayOf("*.twig")),
    Pair(arrayOf("txt"), arrayOf("*.txt")),
    Pair(arrayOf("typoscript"), arrayOf("*.typoscript", "*.ts")),
    Pair(arrayOf("typst"), arrayOf("*.typ")),
    Pair(arrayOf("usd"), arrayOf("*.usd", "*.usda", "*.usdc")),
    Pair(arrayOf("v"), arrayOf("*.v", "*.vsh")),
    Pair(arrayOf("vala"), arrayOf("*.vala")),
    Pair(arrayOf("vb"), arrayOf("*.vb")),
    Pair(arrayOf("vcl"), arrayOf("*.vcl")),
    Pair(arrayOf("verilog"), arrayOf("*.v", "*.vh", "*.sv", "*.svh")),
    Pair(arrayOf("vhdl"), arrayOf("*.vhd", "*.vhdl")),
    Pair(arrayOf("vim"), arrayOf(
        "*.vim", ".vimrc", ".gvimrc", "vimrc", "gvimrc", "_vimrc", "_gvimrc",
    )),
    Pair(arrayOf("vimscript"), arrayOf(
        "*.vim", ".vimrc", ".gvimrc", "vimrc", "gvimrc", "_vimrc", "_gvimrc",
    )),
    Pair(arrayOf("vue"), arrayOf("*.vue")),
    Pair(arrayOf("webidl"), arrayOf("*.idl", "*.webidl", "*.widl")),
    Pair(arrayOf("wgsl"), arrayOf("*.wgsl")),
    Pair(arrayOf("wiki"), arrayOf("*.mediawiki", "*.wiki")),
    Pair(arrayOf("xml"), arrayOf(
        "*.xml", "*.xml.dist", "*.dtd", "*.xsl", "*.xslt", "*.xsd", "*.xjb",
        "*.rng", "*.sch", "*.xhtml",
    )),
    Pair(arrayOf("xz"), arrayOf("*.xz", "*.txz")),
    Pair(arrayOf("yacc"), arrayOf("*.y")),
    Pair(arrayOf("yaml"), arrayOf("*.yaml", "*.yml")),
    Pair(arrayOf("yang"), arrayOf("*.yang")),
    Pair(arrayOf("z"), arrayOf("*.Z")),
    Pair(arrayOf("zig"), arrayOf("*.zig")),
    Pair(arrayOf("zsh"), arrayOf(
        ".zshenv", "zshenv",
        ".zlogin", "zlogin",
        ".zlogout", "zlogout",
        ".zprofile", "zprofile",
        ".zshrc", "zshrc",
        "*.zsh",
    )),
    Pair(arrayOf("zstd"), arrayOf("*.zst", "*.zstd")),
)
